### ISSUE TITLE
Not working on Anki's Version 2.1.26 (70784154)

### ISSUE THREAD

**Issue by gleisonkz** [Cardosaum/anki-addons#1]
Hi I'm trying to use your addon and I got that message below:

![image](https://user-images.githubusercontent.com/48810597/116913155-83322f80-ac1f-11eb-9365-46f2a4855787.png)

I've disabled all my other addons and still getting the same error.

Did you know what is going on?

**Comment by Cardosaum** [comment]
Hi!

I apologize, I didn't setup compatible versions correctly. I suspect you are using Anki with a version number `< 2.1.28`, I'm I right?

The issue here is that my addon make use of `main_window_did_init` hook, but it was introduced in `2.1.28` (AFAIK), so this seems to be the reason you are not able to use the addon. 

I'll update version requirements in AnkWeb.

**Comment by Cardosaum** [comment]
Oh, I'm so sorry, I didn't read carefully your title. 

Yeah... I'd say you'll need to update to at least version `2.1.28` to use this addon.

**Comment by gleisonkz** [comment]
> Oh, I'm so sorry, I didn't read carefully your title.
> 
> Yeah... I'd say you'll need to update to at least version `2.1.28` to use this addon.

Ok man, thanks for your help.
